### ISSUE TITLE
Feature Request: Double click opens file in new tab

### ISSUE THREAD

**Issue by zlee-personal** [MatrixForChange/files-viewer#20]
Currently, double clicking on a file opens it in the current tab, replacing whatever was there.  It would be nice if it opened it in a new tab, or if there was an option to do so in the right-click menu.  Great plugin by the way.

**Comment by yjqww6** [comment]
I used to push a commit(#12) about this,

https://github.com/MatrixForChange/files-viewer/blob/8cadc38ca8c0d631ad219ed6e0754a1458d1f938/tool.rkt#L182-L185

and I agree it's still weird while browsing library code. I may prefer one more condition: only when the editor has no file associated.
@Syntacticlosure , what do you think of it?
