### ISSUE TITLE
Strange blank lines when the popup menu is at the bottom of the screen

### ISSUE THREAD

**Issue by Aloxaf** [MatrixForChange/files-viewer#28]
# Actual
![Screenshot_20190317_120758](https://user-images.githubusercontent.com/17017672/54485060-54c13100-48ad-11e9-8c56-abef5de3bcf6.png)

# Expected
![Screenshot_20190317_120938](https://user-images.githubusercontent.com/17017672/54485079-918d2800-48ad-11e9-8463-1f79475be4bc.png)

- Racket version: 7.2
- System: Arch Linux
- Desktop environment: KDE

**Comment by yjqww6** [comment]
Fixed in https://github.com/racket/gui/pull/122
