### ISSUE TITLE
Internal Error when right-clicking

### ISSUE THREAD

**Issue by JMY1993** [MatrixForChange/files-viewer#29]
OS: macOs
DrRacket version: 7.2
Problem: 
1. right click the file manager, a "DrRacket Internal Error" window shows:
![Screen Shot 2019-04-12 at 11 37 39](https://user-images.githubusercontent.com/16584615/56010728-66b0bb00-5d17-11e9-9d8a-b1eab6705c66.png)
2. close the error window or not, no further response when right-clicking the file manager.
Error Message:
for: expected a sequence for i, got something else: #f
  context...:
   /Applications/Racket v7.2/collects/racket/private/for.rkt:530:2: make-sequence
   /Users/jmy/Library/Racket/7.2/pkgs/files-viewer/private/popup-menu.rkt:20:4: get-workspaces+refresh
   /Users/jmy/Library/Racket/7.2/pkgs/files-viewer/private/popup-menu.rkt:37:4: on-demand method in files-popup-menu%
   /Applications/Racket v7.2/share/pkgs/gui-lib/mred/private/mrwindow.rkt:131:30
   /Applications/Racket v7.2/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /Applications/Racket v7.2/collects/racket/private/more-scheme.rkt:265:2: call-with-exception-handler
   /Applications/Racket v7.2/collects/racket/private/more-scheme.rkt:148:2: call-with-break-parameterization
   /Applications/Racket v7.2/collects/racket/private/more-scheme.rkt:265:2: call-with-exception-handler
   /Applications/Racket v7.2/share/pkgs/gui-lib/mred/private/wx/cocoa/window.rkt:815:4: dispatch-on-event method in window%
   /Applications/Racket v7.2/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:435:6
   /Applications/Racket v7.2/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:486:32
   /Applications/Racket v7.2/share/pkgs/gui-lib/mred/private/wx/common/queue.rkt:634:3

**Comment by Syntacticlosure** [comment]
This bug has been fixed in https://github.com/MatrixForChange/files-viewer/commit/ba1aad28664801711afe9588421040ff74d58100.
Need your reply.

**Comment by JMY1993** [comment]
@Syntacticlosure Hi, the bug has been fixed. Thank you.
