### ISSUE TITLE
hidden files/folders visible 

### ISSUE THREAD

**Issue by spdegabrielle** [MatrixForChange/files-viewer#36]
![Screenshot 2020-04-24 at 14 10 41](https://user-images.githubusercontent.com/108047/80216453-f761ec80-8635-11ea-8ca3-409d31a0774b.png)

I've not tested on linux/windows

**Comment by Syntacticlosure** [comment]
![image](https://user-images.githubusercontent.com/22510026/80223610-1636a200-867b-11ea-9309-025e4bc76a15.png)
Have you ever tried 'Hide dot prefix files and directories'

**Comment by spdegabrielle** [comment]
How do you find that filter?

**Comment by spdegabrielle** [comment]
My mistake - I found it.
Can we change the default?

**Comment by spdegabrielle** [comment]
this looks like it should be resolve by #38
I'll close after a final test.
