### ISSUE TITLE
Follow DrRacket Color Scheme preferences (includes support for dark mode)

### ISSUE THREAD

**Issue by branneman** [MatrixForChange/files-viewer#46]
As already proposed by @AlexKnauth in [this comment](https://github.com/MatrixForChange/files-viewer/issues/32#issuecomment-623753592) (and [this one](https://github.com/MatrixForChange/files-viewer/issues/32#issuecomment-627714183)), I think this project should follow [DrRacket Color Scheme preferences](https://docs.racket-lang.org/drracket/color-scheme.html). Dark modes are very popular nowadays as more and more users are realising they should be more careful with their eyes.

![DrRacket File Viewer Explorer Manager](https://user-images.githubusercontent.com/172579/115584132-0f586480-a2ba-11eb-9b97-2cdcd5391f84.png)

Lastly, thanks for providing this plugin for DrRacket, it's a must-have for any modern software which calls itself an IDE if you ask me :)

**Comment by spdegabrielle** [comment]
Hi @branneman 

I think this project accepts pull requests if you are able to make the necessary changes?

Stephen

**Comment by yjqww6** [comment]
I have made progress in this. I hope it could be merged soon.
<img width="549" alt="图片" src="https://user-images.githubusercontent.com/6269269/115706978-cd561e00-a3a0-11eb-9cb4-39e136ae04d6.png">
