### ISSUE TITLE
feature request: default to folder of current open file.

### ISSUE THREAD

**Issue by spdegabrielle** [MatrixForChange/files-viewer#5]
Hi, 
I really like this plugin, but I found the blank sidebar confusing at first.

Could it default to the folder for the current open file?

Kind regards, 

Stephen

**Comment by Syntacticlosure** [comment]
The feature is a little difficult to implement.
For simplicity , is setting the directory default to (find-system-path 'home-dir) a good idea?

**Comment by spdegabrielle** [comment]
Yes, setting the directory default to (find-system-path 'home-dir) is a good idea!
